- hosts: localhost
  environment:
    KUBECONFIG: ./output/config
  vars:
    cert_manager_chart_ref: jetstack/cert-manager
    namespace: cert-manager
    chart_version: 1.5.3
  tasks:
    - name: Add cert manager repo
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: "https://charts.jetstack.io"

    - name: Deploy cert manager
      community.kubernetes.helm:
        name: cert-manager
        chart_ref: "{{ cert_manager_chart_ref }}"
        chart_version: "{{ chart_version }}"
        release_namespace: "{{ namespace }}"
        create_namespace: true
        values:
          installCRDs: true